- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Add Homebrew taps
  homebrew_tap: tap={{ item }}
  with_items:
    - caskroom/cask
    - caskroom/fonts
    - caskroom/versions

- name: Simple HTTP/2 Server
  homebrew_tap:
    name: GoogleChrome/simplehttp2server
    url: 'https://github.com/GoogleChrome/simplehttp2server'
